service: email-api

provider:
  name: aws
  runtime: python3.9

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000  # Use port 4000 instead of default 3002

functions:
  sendEmail:
    handler: handler.send_email
    events:
      - http:
          path: send-email
          method: post
          cors: true
